baseURL = "/"
languageCode = "nl-nl"
title = "Rusland 1"
#theme = "cupper-hugo-theme"
theme = "hugo-freelancer-theme"
relativeURLs = true
canonifyURLs = false

summarylength = 40

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"
disableKinds = ["RSS"]


[taxonomies]
  tag = "tags"
  genre = "genres"
  categorie = "categorieën"
  onderwerp = "onderwerpen"
  artiest = "artiesten"

[params]

    name = "Mr. Hugo"
    description = "My awesome description"

    email = "your@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Mr. Hugo's Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Mr. Hugo"
        subtitle = "Blogger - Programmer - Gopher"

    [params.portfolio]

        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization."
        right = "Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!"

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["3481 Melrose Place", "Beverly Hills, CA 90210"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/spf13/hugo"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/questions/tagged/hugo"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."




  favicon = ""
  description = "over Rusland"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[menu]
#  [[menu.nav]]
#    name = "Home"
#    url = "/"
#    weight = 1
  [[menu.nav1]]
    name = "Taal"
    url = "/taal/"
    weight = 2
  [[menu.nav1]]
    name = "Muziek"
    url = "/muziek/"
    weight = 3
  [[menu.nav1]]
    name = "Land en Volk"
    url = "/land-en-volk/"
    weight = 4

#  [[menu.nav]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 6
#
  [[menu.nav2]]
    name = "Genres"
    url = "/genres/"
    weight = 7
#
#  [[menu.nav]]
#    name = "Artiesten (mzk)"
#    url = "/artiesten/"
#    weight = 7
#
  [[menu.nav2]]
    name = "Onderwerpen"
    url = "/onderwerpen/"
    weight = 8

  [[menu.nav2]]
    name = "Categorieën"
    url = "/categorieën/"
    weight = 9

